# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build page
      run: npm run build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDL+Jb0+Yjsg2l5cqyPbLlygHx8UFKrBQFAFzWhDqjAgMg/UOMkaHJduVvXlwRaNdZeKMBlCxWjrNmZeqrUl3vKJRuXnquguOyE8S+L9jH8uX+KBJGF4bCa0SgTEmugBrTUvPf5XVifLVYbVSlfXgHRN3y/h32PCsThZI+SpEQuPeEsbTUSok7R9O1iocaW9tiyG+EPBd2NHxXps5ba7DIX5virkV8A6X/zS0P/VSXL7TCJ4khKTMZ9DjkE/NLqt3VYiz1QNVTpYpdbXcD2u/5AZ8kx/dvMK8gQAvUEXvgp0USGWAJD97rlSlclOVX1zmPy6iMBO1v3u7fsBzr266WT7fdyhiRD2yceB+QVO7k/2suB8+1Dy4bbv+5+oKuq2IDclTY5AFJwwAunediYUoKKNclCZrFPEjon1pTSGDYeHBCwsEb83bottcT27vq1fi9Ao+l0FHTTdha1kxOQClxynb8LjclXwoZWF2yJJSPFZNPX+lgspA5P4R+OEGKc8PpWBKW3Y7ERckspQ3svk1DFP47XywIvmBQDZMfrTm/PzggL1C0CpYV7GCnwQGYxj4kHUifUWnvUDTLlPrjvwl5JmPir6n4NkMGG1IsrHjepqGwi+y6tw9aybREVKfxEE/L5jXbfUNpo/TAWf+dwgas+Dh3BbjbGLCU5mQZ7Z1quYw== $(git config vitpth@gmail.com)
        publish_dir: ./build
